<a href="https://colab.research.google.com/github/David-Arciniegas/Tarea-11-MN/blob/main/Tarea_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

def gauss_jacobi(A, b, tol=1e-3, max_iter=100):
    n = len(b)
    x = np.zeros(n)
    x_new = np.zeros(n)

    for iteration in range(max_iter):
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]

        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            print(f"convergencia despues de {iteration+1} iteraciones")
            return x_new

        x = x_new.copy()

    print("iteraciones maximas antes de obtener una convergencia")
    return x

# Ejemplo de uso:
# A = np.array([[3, -1, 1], [3, 6, 2], [3, 3, 7]])
# b = np.array([1, 0, 4])
# x = gauss_jacobi(A, b, tol=1e-3, max_iter=2)
# print(x)


In [20]:
#Ejercicio de la pregunta 1
# Ejercicio a
A = np.array([[3, -1, 1], [3, 6, 2], [3, 3, 7]])
b = np.array([1, 0, 4])
x = gauss_jacobi(A, b, tol=1e-3, max_iter= 20)
print(x)

# Ejercicio b
A = np.array([[10, -1, 0], [-1, 10, -2], [0, -2, 10]])
b = np.array([9, 7, 6])
x = gauss_jacobi(A, b, tol=1e-3, max_iter= 20)
print(x)

# Ejercicio c
A = np.array([[10, 5, 0, 0], [5, 10, -4, 0], [0, -4, 8, -1], [0, 0, -1, 5]])
b = np.array([6, 25, -11, -11])
x = gauss_jacobi(A, b, tol=1e-3, max_iter= 40)
print(x)

# Ejercicio d
A = np.array([[4, 1, 1, 0, 1], [-1, -3, 1, 1, 0], [2, 1, 5, -1, -1], [-1, -1, -1, 4, 0], [0, 2, -1, 1, 4]])
b = np.array([6, 6, 6, 6, 6])
x = gauss_jacobi(A, b, tol=1e-3, max_iter= 50)
print(x)

convergencia despues de 9 iteraciones
[ 0.03510079 -0.23663751  0.65812732]
convergencia despues de 6 iteraciones
[0.995725 0.957775 0.79145 ]
convergencia despues de 21 iteraciones
[-0.79710581  2.79517067 -0.25939578 -2.25179299]
convergencia despues de 12 iteraciones
[ 0.78708833 -1.00303576  1.86604817  1.91244923  1.98957067]


In [50]:
def gauss_seidel(A, b, tol=1e-6, max_iter=100):
    n = len(b)
    x = np.zeros(n)

    for iteration in range(max_iter):
        x_new = np.copy(x)

        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]

        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            print(f"convergencia despues de {iteration+1} iteraciones")
            return x_new

        x = x_new

    print("iteraciones maximas sin convergencia")
    return x

# Ejemplo de uso:
# A = np.array([[3, -1, 1], [3, 6, 2], [3, 3, 7]])
# b = np.array([1, 0, 4])
# x = gauss_seidel(A, b, tol=1e-3, max_iter=2)
# print(x)


In [21]:
#Ejercicio de la pregunta 1
# Ejercicio a
A = np.array([[3, -1, 1], [3, 6, 2], [3, 3, 7]])
b = np.array([1, 0, 4])
x = gauss_seidel(A, b, tol=1e-6, max_iter= 20)
print(x)

# Ejercicio b
A = np.array([[10, -1, 0], [-1, 10, -2], [0, -2, 10]])
b = np.array([9, 7, 6])
x = gauss_seidel(A, b, tol=1e-6, max_iter= 20)
print(x)

# Ejercicio c
A = np.array([[10, 5, 0, 0], [5, 10, -4, 0], [0, -4, 8, -1], [0, 0, -1, 5]])
b = np.array([6, 25, -11, -11])
x = gauss_seidel(A, b, tol=1e-6, max_iter= 30)
print(x)

# Ejercicio d
A = np.array([[4, 1, 1, 0, 1], [-1, -3, 1, 1, 0], [2, 1, 5, -1, -1], [-1, -1, -1, 4, 0], [0, 2, -1, 1, 4]])
b = np.array([6, 6, 6, 6, 6])
x = gauss_seidel(A, b, tol=1e-6, max_iter= 20)
print(x)

convergencia despues de 11 iteraciones
[ 0.03508794 -0.23684206  0.65789462]
convergencia despues de 7 iteraciones
[0.99578947 0.95789473 0.79157895]
convergencia despues de 18 iteraciones
[-0.79764636  2.79529348 -0.25882387 -2.25176477]
convergencia despues de 12 iteraciones
[ 0.78663237 -1.0025707   1.86632389  1.91259639  1.98971722]


In [33]:
# Ejercicio 5
A = np.array([[2, -1, 1], [2, 2, 2], [-1, -1, 2]])
b = np.array([-1, 4, -5])
x = gauss_jacobi(A, b, tol=1e-3, max_iter= 1000)
print(x)

x = gauss_seidel(A, b, tol=1e-5, max_iter= 30)
print(x)

iteraciones maximas antes de obtener una convergencia
[-1.71063658e+48 -6.84254632e+48  1.71063658e+48]
convergencia despues de 23 iteraciones
[ 1.00000226  1.9999975  -1.00000012]


In [37]:
#diagonal estrictamente dominante
def DED(matriz):
    n = matriz.shape[0]
    for i in range(n):
        suma_fila = sum(abs(matriz[i, j]) for j in range(n) if j != i)
        if abs(matriz[i, i]) <= suma_fila:
            return False, i+1
    return True, None

In [45]:
# Ejercicio 6
A = np.array([[1, 0, -1], [-1/2, 1, -1/4], [1, -1/2, 1]])
b = np.array([0.2, -1.425, 2])


In [39]:
result, fila = DED(A)

if result:
    print("es diagonal estrictamente dominante.")
else:
    print(f"no es diagonal estrictamente dominante en la fila {fila}")

no es diagonal estrictamente dominante en la fila 1


In [44]:
x = gauss_seidel(A, b, tol=1e22, max_iter= 300)
print(x)

convergencia despues de 1 iteraciones
[ 0.2    -1.325   1.1375]


In [49]:
# Ejercicio 7
x = gauss_jacobi(A, b, tol=1e22, max_iter= 300)
print(x)

convergencia despues de 1 iteraciones
[ 0.2   -1.425  2.   ]


In [51]:
# Ejercicio 8
A = np.array([
    [4, -1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],[-1, 4, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0],[0, -1, 4, -1, 0, 0, 0, 0, 0, 0, 0, 0],[0, 0, -1, 4, 0, 0, -1, 0, 0, 0, 0, 0],[-1, 0, 0, 0, 4, -1, 0, 0, 0, 0, 0, 0],[0, 0, 0, 0, -1, 4, 0, 0, -1, 0, 0, 0],[0, 0, 0, -1, 0, 0, 4, -1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, -1, 4, -1, 0, 0, 0],[0, 0, 0, 0, 0, -1, 0, -1, 4, 0, 0, -1],[0, 0, 0, 0, 0, 0, 0, 0, 0, 4, -1, 0],[0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 4, -1],[0, 0, 0, 0, 0, 0, 0, 0, -1, 0, -1, 4]
])
b = np.array([220, 110, 110, 220, 110, 110, 110, 110, 220, 110, 110, 220])


In [52]:
result, fila = DED(A)

if result:
    print("es diagonal estrictamente dominante.")
else:
    print(f"no es diagonal estrictamente dominante en la fila {fila}")

es diagonal estrictamente dominante.


In [53]:
x = gauss_jacobi(A, b, tol=1e-2, max_iter= 100)
print(x)

x = gauss_seidel(A, b, tol=1e-2, max_iter= 100)
print(x)

convergencia despues de 15 iteraciones
[ 88.56189051  66.18473877  66.18473877  88.56189051  68.07105926
  73.73321353  68.07105926  73.73321353 116.87473866  43.33541929
  63.34492734 100.05204068]
convergencia despues de 10 iteraciones
[ 88.56398155  66.18712394  66.18754444  88.56541646  68.07550445
  73.73968709  68.0759504   73.73979858 116.88434376  43.33707837
  63.34874193 100.05827142]
